sudo: required
dist: bionic

os: linux

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
    - liblua5.1-0-dev

env:
  matrix:
    - LUA=lua5.1-dev LUA_DEV=liblua5.1-dev LUA_INCLUDE_DIR=/usr/include/lua5.1 LUA_CMODULE_DIR=/usr/lib/lua/5.1 LUALIB=-llua5.1
    - LUA=libluajit-5.1-dev LUA_DEV=libluajit-5.1-dev LUA_INCLUDE_DIR=/usr/include/luajit-2.0 LUA_CMODULE_DIR=/usr/lib/lua/5.1 LUALIB=-lluajit-5.1

before_install:
    - git clone https://github.com/openresty/lua-cjson.git

install:
    - sudo apt-get install -qq -y $LUA luarocks cppcheck valgrind
    - sudo apt-get install -qq -y cpanminus libipc-run3-perl > build.log 2>&1 || (cat build.log && exit 1)
    - sudo cpanm --notest Test::Base Test::LongString > build.log 2>&1 || (cat build.log && exit 1)

script:
  - cppcheck --force --error-exitcode=1 --enable=warning . > build.log 2>&1 || (cat build.log && exit 1)
  - cd lua-cjson/ && make && sudo make install && cd ..
  - make test valtest

