sudo: required
dist: bionic

os: linux

language: c

compiler:
  - gcc

env:
  matrix:
    - LUA=1 LUA_INCLUDE_DIR=/usr/include/lua5.1 LUA_CMODULE_DIR=/usr/lib/lua/5.1 LUALIB=-llua5.1
    - LUAJIT=1 LUAJIT_PREFIX=/usr/local LUA_INCLUDE_DIR=/usr/include/luajit-2.1 LUA_CMODULE_DIR=/usr/lib/lua/5.1 LUALIB=-lluajit-5.1

before_install:
    - git clone https://github.com/openresty/lua-cjson.git

install:
    - > if [ -n "$LUAJIT" ]; then
            git clone -b v2.1-agentzh https://github.com/openresty/luajit2.git
            cd ./luajit2 || exit 1
            make -j$JOBS CCDEBUG=-g Q= PREFIX=$LUAJIT_PREFIX CC=$CC XCFLAGS='-DLUA_USE_APICHECK -DLUA_USE_ASSERT'
            sudo make install > build.log 2>&1 || (cat build.log && exit 1)
        fi
    - > if [ -n "$LUA" ]; then
            sudo apt-get install -qq -y liblua5.1-dev
        fi
    - sudo apt-get install -qq -y luarocks cppcheck valgrind
    - sudo apt-get install -qq -y cpanminus libipc-run3-perl > build.log 2>&1 || (cat build.log && exit 1)
    - sudo cpanm --notest Test::Base Test::LongString > build.log 2>&1 || (cat build.log && exit 1)

script:
  - cppcheck --force --error-exitcode=1 --enable=warning . > build.log 2>&1 || (cat build.log && exit 1)
  - cd lua-cjson/ && make && sudo make install && cd ..
  - make test valtest

